services:
  - type: web
    name: tim-crm-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: https://mnzzeuqxzrfsqiynfgmy.supabase.co
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false